###
GET http://localhost:3000/users
###
POST http://localhost:3000/users
content-type: application/json

{
  "nome": "teste",
  "nome_social": "teste2",
  "cpf_cnpj": "3234567891",
  "email": "teste@io.com",
  "senha": "senha",
  "nivel": "CLIENTE",
  "telefone": "9876543",
  "restricao_alimenticia": "Leite",
  "logradouro": "Teste",
  "numero": "123A",
  "bairro": "teste",
  "cidade": "Teste",
  "estado": "CE"
}
###
PUT http://localhost:3000/users/1234567890
content-type: application/json

{
  "nome": "",
  "nome_social": null,
  "email": "teste@io.com",
  "senha": "123456",
  "nivel": "CLIENTE",
  "telefone": "",
  "restricao_alimenticia": "Leite"
}
###
PUT http://localhost:3000/users/3234567890/delete
content-type: application/json

{
  "nome": "Emanuel Victor",
  "nome_social": null,
  "email": "teste@io.com",
  "senha": "123456",
  "ativo": false,
  "nivel": "ADMINISTRADOR",
  "telefone": "",
  "restricao_alimenticia": "Leite"
}
###