###
GET http://localhost:3000/users
###
POST http://localhost:3000/users
content-type: application/json

{
  "nome": "teste",
  "nome_social": "teste2",
  "cpf_cnpj": "3234567893",
  "email": "teste@email.com",
  "senha": "123456",
  "nivel": "ADMINISTRADOR",
  "telefone": "9876543",
  "restricao_alimenticia": "Leite",
  "logradouro": "Teste",
  "numero": "123A",
  "bairro": "teste",
  "cidade": "Teste",
  "estado": "CE"
}
###
PUT http://localhost:3000/users/3234567893
content-type: application/json

{
  "senha": "1234567"
}
###
PUT http://localhost:3000/users/3234567893/delete
###